### add concert
GET localhost:8080/concert?name=allenconcert

### get Token
POST http://localhost:8080/token
Content-Type: application/json

{
  "userId": 999
}

### add Token
POST http://localhost:8080/token
Content-Type: application/json

{
  "userId": 999
}


### add concert option
POST localhost:8080/concert/options
Content-Type: application/json

{
  "concertId": 1,
  "reservationOpenAt": "2024-10-03 13:00:00",
  "schedule": "2024-12-26 19:00:00",
  "price": 100000,
  "ticketAmount": 70
}

### find seat status
GET localhost:8080/concert/seats/state?concert_schedule_id=2
Content-Type: application/json
Token: c0cb5f0f-cf23-3ab3-99c1-fcd31fff1efc

### reserve concert
POST localhost:8080/concert/reservation
Content-Type: application/json
Token: 13c8ffd9-7701-3703-a701-cf8e11deac65

{
  "userId": 2,
  "concertId": 1,
  "concertDescId": 2,
  "seatNo": 6
}

###
POST https://ijhttp-examples.jetbrains.com/post
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

